name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

env:
  ACR_NAME: welltaxesregistry
  RG_NAME: rg-well-taxes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Orders
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/orders:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/orders:latest \
                       -f WellTaxes.Backend/WellTaxes.Service.Orders/Dockerfile WellTaxes.Backend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/orders --all-tags

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/frontend:latest \
                       --build-arg VITE_API_URL=${{ secrets.BACKEND_URL }} \
                       -f WellTaxes.Frontend/Dockerfile WellTaxes.Frontend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/frontend --all-tags

      - name: Deploy Frontend
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ env.ACR_NAME }}
          containerAppName: welltaxes-frontend
          resourceGroup: ${{ env.RG_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }}

      - name: Deploy Orders
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ env.ACR_NAME }}
          containerAppName: welltaxes-orders
          resourceGroup: ${{ env.RG_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/orders:${{ github.sha }}
          environmentVariables: >
            ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}"
            AzureAd__TenantId="${{ secrets.AZURE_AD_TENANTID }}"
            AzureAd__ClientId="${{ secrets.AZURE_AD_CLIENTID }}"
            AzureAd__Audience="${{ secrets.AZURE_AD_AUDIENCE }}"
            AzureAd__Scopes="${{ secrets.AZURE_AD_AUDIENCE }}"
            AzureAd__Instance="https://login.microsoftonline.com/"
            Swagger__ClientId="${{ secrets.AZURE_AD_CLIENTID }}"
            Swagger__ClientSecret="${{ secrets.AZURE_AD_CLIENTSECRET }}"
