name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

env:
  ACR_NAME: welltaxesregistry
  RG_NAME: rg-well-taxes

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Orders
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/orders:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/orders:latest \
                       -f WellTaxes.Backend/WellTaxes.Service.Orders/Dockerfile WellTaxes.Backend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/orders --all-tags

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/frontend:latest \
                       -f WellTaxes.Frontend/Dockerfile WellTaxes.Frontend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/frontend --all-tags

      - name: Deploy Frontend
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{ env.ACR_NAME }}
          containerAppName: welltaxes-frontend
          resourceGroup: ${{ env.RG_NAME }}
          imageToDeploy: ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }}