name: Build and Push to ACR

on:
  push:
    branches: [ "main" ]

env:
  ACR_NAME: welltaxesregistry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/docker-login@v1
        with:
          login-server: welltaxesregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Gateaway
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/gateaway:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/gateaway:latest \
                       -f WellTaxes.Backend/WellTaxes.Service.Gateaway/Dockerfile WellTaxes.Backend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/gateaway --all-tags

      - name: Build and Push Orders
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/orders:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/orders:latest \
                       -f WellTaxes.Backend/WellTaxes.Service.Orders/Dockerfile WellTaxes.Backend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/orders --all-tags

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }} \
                       -t ${{ env.ACR_NAME }}.azurecr.io/frontend:latest \
                       -f WellTaxes.Frontend/Dockerfile WellTaxes.Frontend/
          docker push ${{ env.ACR_NAME }}.azurecr.io/frontend --all-tags